version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
  app:
    image: 'tablebook'
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGODB_CONNECTION_STRING: mongodb://mongodb:27017/tablebook_dev
      SECRET: tyhstghse5gegse
