version: '3.8'
services:
  mongodb:
    image: mongo:latest
    network_mode: "host"
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

  client:
    image: client
    network_mode: "host"
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/usr/src/app/client
    ports:
      - 5173:5173
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  server:
    image: server
    network_mode: "host"
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/usr/src/app/server
    environment:
      - PORT=8080
      - MONGODB_DEV_CONNECTION_STRING=mongodb://localhost:27017/tablebook_dev
    ports:
      - 8080:8080
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped