services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    attach: false
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGODB_CONNECTION_STRING: mongodb://mongodb:27017/tablebook_dev
      SECRET: devsecretnottobeusedinproduction
