name: Branch Verification

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verification:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Fetch code
        uses: actions/checkout@v4.1.1

      - name: Install Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20.x"

      - name: Install the Server dependencies
        working-directory: ./server
        run: npm ci

      - name: Run Lint on Server
        working-directory: ./server
        run: npm run lint

      - name: Run tests on Server
        working-directory: ./server
        run: npm test
        env:
            SECRET: testsecret

      - name: Install the Client dependencies
        working-directory: ./client
        run: npm ci

      - name: Run Lint on Client
        working-directory: ./client
        run: npm run lint

      - name: Run tests on Client
        working-directory: ./client
        run: npm test

      - name: Build the Client
        working-directory: ./client
        run: npm run build

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '6.0'

      - name: Start server
        working-directory: ./server
        run: npm start & # "&" should leave the server running
        env:
          SECRET: testsecret
          MONGODB_CONNECTION_STRING: mongodb://localhost:27017/tablebook_test
          PORT: 8080

      - name: Install E2E test dependencies
        working-directory: ./e2e
        run: npm ci

      - name: Run end-to-end tests
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BASE_URL: http://localhost:8080
        with:
          command: npm test
          wait-on: http://localhost:8080
          working-directory: ./e2e
